---
name: GoogleMapBasic
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Sunnysideup\GooglemapBasic\Model\GoogleMapBasic

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\GooglemapBasic\Control\GoogleMapBasicController
