---
name: GoogleMapBasic
---
SilverStripe\CMS\Model\SiteTree:
    extensions:
        - Sunnysideup\GooglemapBasic\Model\GoogleMapBasic
PageController:
    extensions:
        - Sunnysideup\GooglemapBasic\Control\GoogleMapBasicController
